### ISSUE TITLE
International Internet: "Podium" discussion about Internet use in various countries

### ISSUE THREAD

**Issue by martinheidegger** [owddm/presentations#1]
I thought last time that it would be nice to have a discussion of 5(?) members from different countries talking about internet platforms, web developer tools, currency/language specific problems when working-for/working-with/using the internet in their specific country. I would be happy to play "host" (asking questions).

What do you think of the idea?
Would want to be on the podium? (if yes, from which country are you?)

**Comment by hostragon-hosting** [comment]
Great idea!
![allen](https://cloud.githubusercontent.com/assets/9048872/6568501/bfd1852a-c71b-11e4-9695-53f7a753eb83.png)

**Comment by martinheidegger** [comment]
I have been talking to @frankyxhl and he seems to be fine to talk about china it if no other plans arise. Also last week I talked to a few people from Afghanistan that might come.

**Comment by coliff** [comment]
Cool. An interesting idea. I'd be happy to cover the UK and talk a bit about what I know about the Industry there and answer any questions about that.

**Comment by frankyxhl** [comment]
Fishbowl conversation?**Love it**!
My friends in Shanghai will take a trip to Japan in this end of March.They want me go to Tokyo together....However,the schedule has still not been made.I will try my best to handle this.

**Comment by martinheidegger** [comment]
@coliff for uk!
@frankyxhl for china!
@SachaG for france!
@frankyxhl's friend for korea?

**Comment by martinheidegger** [comment]
Question catalog (so we can prepare a little, no need to answer here):

Education:
- What year did you first hear about the Internet? 
- Did someone/something inspire you to start learning design/programming?
- How did you find out that developing for  the Internet is a way to earn a living?
- Where did information about the Internet came from? (Public channel? Company? NPO?)
- Do/did you study in your mother-tongue?
- What is the most famous developer/designer you knew when starting out? (What does he do?)
- Do you know any good newspapers/blogs that cover this topic and write in non-english?
- Are there degrees/certificates that make a difference in your hiring process?
- Have the people you are working with a university degree?
- How strong is your connection to the teacher of your profession?

Infrastructure:
- How did your first access to the internet look like?
- How is the distribution of Wifi in your country?
- What are well known hosting solutions in your area?
- How do you (/ What providers do you use to) register a internet domain?
- Is the internet connection in your country stable?
- How do you connect with people outside of the country using the internet?
- How did you get your first computer?
- How do you get hardware now?
- How far are places where you can meet other designers/developers?

(more to come)

**Comment by frankyxhl** [comment]
I just got message from Korean friend. Something happened, so he changed his staying plan in Osaka and will go back to Seoul tomorrow. Sorry,guys.

**Comment by martinheidegger** [comment]
@coliff for uk!
@frankyxhl for china!
@SachaG for france!
@Jamcgrath for hawaii(us)!
@bebensiganteng for indonesia!

**Comment by SachaG** [comment]
I have to confess I've almost always browsed the U.S. Internet, not the French one… Hopefully I'll still be able to contribute something to the discussion despite that!

**Comment by martinheidegger** [comment]
@SachaG I think that is okay.

A few more questions for the catalog:

Government:
- How much of your government business do you do electronically?
- What do your have to look out for when publishing a website (ecommerce laws, copyright etc.)?
- (how) Does the government influence technical, editorial or strategical decisions?
- Do you know how to get a government contract?
- How does the community in your country think of open data?
- How big of a deal are military/political spendings in your country? Is it easy to get a job in politics?

Business:
- What is the ratio of small / big businesses where you are from?
- How relevant is your education in business?
- What rank do programmers/designers have in a company?
- What is a good salary in your country? (for designer/programmer/anyone)
- What do you need to write on a bill?
- How would you promote your e-commerce business?
- What is the thing easiest to sell to a client? (banner? webgames? responsive design? campaigns?, ...)

Diversity:
- Did you learn/Do you have to think of accessibility? 
- How is the man/woman ratio at an average workplace?
- How would you like it to be?
- How are women, interested in technology, treated in school?
- Did you have technical female teachers/instructors?

Communication:
- What forums do/did you use?
- How important is email/twitter/facebook/linkedin for your work?
- What do you need to care for when first meeting a customer?
- When is the best time to exchange contacts in your line of work?
- Do you encrypt your communication?
- Are there places that are hard to interact with because of security reasons?
- Are there places that are hard to interact with because of technical problems?

Technical:
- What CMS do you know is used in business (beside wordpress)?
- What is your way to make sure software is working fine?
- What do you understand under "data security?"
- Is there a Tax/Billing software that you often use or hear of?
- Can you mention one important thing related to translation/localisation?
- What is the most common technical problem of customers with your project?
- Where do you host what kind of server?
- How is Mac/Windows - iOS/Android/FirefoxOS/Windows perceived at home?
- JSON/XML/Excel/Zip/PDF/Dropbox/FTP how do you exchange data?
- What do you prepare for a "testsite" where your customers check your project?
- What is part of a delivery?
- What is part of your responsibility as developer/designer?

**Comment by martinheidegger** [comment]
You don't need to prepare anything btw. It would be good if your read over the list and send me some links so we can have them handy in case they are interesting
