### ISSUE TITLE
Niklas a fullstack MEAN developer from Sweden

### ISSUE THREAD

**Issue by soulgrasp** [owddm/presentations#3]
Hi Guys and Girls in the Multiverse!!

My name is Niklas and i'm a developer from Sweden who recently found my way to Osaka by love.
Food is great, weather has finally started to become good and the development environment for me as a non Japanese developer is to say the least --={"Ice Age"}=--- :)
I'm currently freelancing back to Sweden but looking for something more conventional here!!

Recently i've developed a webapp based on mean.js to help doctors survey and monitor the passive exercise of obeses kids (e.g. how much they walk, run and ride the bike in their unorganized leisure time).

Love to talk about this topic.

/Niklas

**Comment by martinheidegger** [comment]
Hello Niklas! I saw that you have been waitlisted, please come anyways! Usually a few people can't show up and there is some space left. We would love to hear about your app!

**Comment by soulgrasp** [comment]
Hello Martin!!

  I hope you have a wonderful day. Thank you for writing I'm very excited
to hear this and will prepare :)

Best Regards Niklas
Den 24 apr 2015 01:28 skrev "Martin Heidegger" notifications@github.com:

**Comment by martinheidegger** [comment]
Thank you!
